name: Vérification de l'arborescence du projet

on:
  pull_request:
    branches:
      - main

jobs:
  check-arborescence:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Vérification de l'arborescence du projet
        run: |
          echo "Vérification de l'arborescence du projet"
          
          # Vérification de la structure de répertoires
          if [ ! -d "site" ]; then
            echo "Le répertoire 'site' est manquant."
            exit 1
          fi
          if [ ! -d "site/img" ]; then
            echo "Le répertoire 'img' est manquant."
            exit 1
          fi
          if [ ! -d "site/css" ]; then
            echo "Le répertoire 'css' est manquant."
            exit 1
          fi
          if [ ! -d "site/js" ]; then
            echo "Le répertoire 'js' est manquant."
            exit 1
          fi
          
          # Vérification des fichiers dans 'site'
          echo "Vérification des fichiers dans 'site'..."
          for file in site/*; do
            if [[ -d "$file" ]]; then
              # Ignore les dossiers comme img, css, js
              continue
            fi
            # Vérification des fichiers .html et .php dans site
            if [[ "$file" == site/*.html || "$file" == site/*.php ]]; then
              continue
            else
              echo "Erreur : Le fichier '$file' dans 'site' n'est ni .html ni .php"
              exit 1
            fi
          done
          
          # Vérification des fichiers dans 'img' (uniquement .png et .jpg)
          echo "Vérification des fichiers dans 'img'..."
          for img in site/img/*; do
            if [[ "$img" != *.png && "$img" != *.jpg ]]; then
              echo "Erreur : Le fichier '$img' dans 'img' n'est ni .png ni .jpg"
              exit 1
            fi
          done
          
          # Vérification des fichiers dans 'css' (uniquement .css)
          echo "Vérification des fichiers dans 'css'..."
          for css in site/css/*; do
            if [[ "$css" != *.css ]]; then
              echo "Erreur : Le fichier '$css' dans 'css' n'est pas un fichier .css"
              exit 1
            fi
          done
          
          # Vérification des fichiers dans 'js' (uniquement .js)
          echo "Vérification des fichiers dans 'js'..."
          for js in site/js/*; do
            if [[ "$js" != *.js ]]; then
              echo "Erreur : Le fichier '$js' dans 'js' n'est pas un fichier .js"
              exit 1
            fi
          done
