name: Vérification des fichiers et arborescence

on:
  pull_request:
    branches:
      - master  # Déclenche l’action uniquement sur une PR vers master

jobs:
  verify-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Vérifier l’arborescence
        run: |
          # Vérification de la structure des répertoires
          if [ ! -d "site" ]; then echo "Erreur: le dossier 'site' n'existe pas."; exit 1; fi
          if [ ! -d "site/img" ]; then echo "Erreur: le dossier 'site/img' n'existe pas."; exit 1; fi
          if [ ! -d "site/css" ]; then echo "Erreur: le dossier 'site/css' n'existe pas."; exit 1; fi
          if [ ! -d "site/js" ]; then echo "Erreur: le dossier 'site/js' n'existe pas."; exit 1; fi
          if [ ! -d "src" ]; then echo "Erreur: le dossier 'src' n'existe pas."; exit 1; fi
          echo "Arborescence correcte."

      - name: Vérifier les extensions des fichiers dans 'site'
        run: |
          # Vérification des fichiers dans 'site'
          find site ! -name '*.html' ! -name '*.php' -type f && exit 1 || echo "OK: site"

      - name: Vérifier les extensions des fichiers dans 'site/img'
        run: |
          # Vérification des fichiers dans 'img'
          find site/img ! -name '*.png' ! -name '*.jpg' -type f && exit 1 || echo "OK: img"

      - name: Vérifier les extensions des fichiers dans 'site/css'
        run: |
          # Vérification des fichiers dans 'css'
          find site/css ! -name '*.css' -type f && exit 1 || echo "OK: css"

      - name: Vérifier les extensions des fichiers dans 'site/js'
        run: |
          # Vérification des fichiers dans 'js'
          find site/js ! -name '*.js' -type f && exit 1 || echo "OK: js"
