name: Afficher les fichiers lors d'un push

on: [push]  # Exécute l'action à chaque push

jobs:
  list_files:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v3  # Clone le repo dans l'environnement GitHub Actions

      - name: Afficher les fichiers
        run: ls -R  # Liste tous les fichiers et dossiers récursivement
