name: Afficher les fichiers et Linter le code

on:
  push:
    branches:
      - mes-dates  # Déclenche l'action uniquement pour la branche mes-dates

jobs:
  list_files:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v3

      - name: Afficher les fichiers
        run: ls -R

  lint_code:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v3

      - name: Installer PHP et Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Installer les dépendances
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Lancer PHP_CodeSniffer (phpcs)
        run: vendor/bin/phpcs src/ --standard=PSR2
